apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: multicluster-observability-addon
  annotations:
    addon.open-cluster-management.io/lifecycle: addon-manager
spec:
  addOnMeta:
    displayName: Multicluster Observability Addon
    description: "multicluster-observability-addon is the addon to configure spoke clusters to collect and forward logs/traces to a given set of outputs"
  supportedConfigs:
    # Describes the general addon configuration applicable for all managed clusters.
    - group: addon.open-cluster-management.io
      resource: addondeploymentconfigs
      defaultConfig:
        name: multicluster-observability-addon
        namespace: open-cluster-management-observability
    # Resources for configuring the deployment of the Metrics collection
    - group: monitoring.rhobs
      resource: scrapeconfigs
    - group: monitoring.rhobs
      resource: prometheusagents
    - group: monitoring.coreos.com
      resource: prometheusrules
    # Resources for configuring the deployment of the Log collection
    - group: observability.openshift.io
      resource: clusterlogforwarders
    # Resources for configuring the deployment of OpenTelemetry collection
    - group: opentelemetry.io
      resource: opentelemetrycollectors
    # Resources for configuring the deployment of OpenTelemetry Instrumentation
    - group: opentelemetry.io
      resource: instrumentations
  installStrategy:
    type: Placements
    placements:
      - name: global
        namespace: open-cluster-management-global-set
        configs:
          - group: observability.openshift.io
            resource: clusterlogforwarders
            name: instance
            namespace: open-cluster-management-observability
          - group: opentelemetry.io
            resource: opentelemetrycollectors
            name: instance
            namespace: open-cluster-management-observability
          - group: opentelemetry.io
            resource: instrumentations
            name: instance
            namespace: open-cluster-management-observability
