{{- if .Values.DeployNonOCPStack }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-exporter.fullname" . }}
  labels:
    {{- include "node-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "node-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}