{{- if .Values.enabled }}
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: mcoa-managed-storage
  namespace: openshift-logging
  labels:
    app: {{ template "loggingStorage.name" . }}
    chart: {{ template "loggingStorage.chart" . }}
    release: {{ .Release.Name }}
spec:
{{- fromJson .Values.lsSpec | toYaml | nindent 2 }}
{{- end }}