apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
  labels:
    operators.coreos.com/cluster-logging.openshift-logging: ''
    app: {{ template "lokihelm.name" . }}
    chart: {{ template "lokihelm.chart" . }}
    release: {{ .Release.Name }}
spec:
  channel: {{ .Values.loggingSubscriptionChannel }}
  installPlanApproval: Automatic
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace
