apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: open-cluster-management
spec:
  outputs:
{{- range $_, $dic := .Values.outputs }}
{{- if eq $dic.type "cloudwatch" }}
   - cloudwatch:
       region: eu-central-1
       groupBy: logType
     type: cloudwatch
{{- else if eq $dic.type "loki" }}
   - loki:
       labelKeys:
       - log_type
       - kubernetes.namespace_name
       - kubernetes.pod_name
       - openshift.cluster_id
     type: "loki"
     url: https://PLACEHOLDER
     tls:
       insecureSkipVerify: true
{{- end }}
     name: {{ $dic.name }}
     secret: 
       name: PLACEHOLDER
{{- end }}
  pipelines:
{{- range $_, $dic := .Values.outputs }}
   - name: infra-{{ $dic.name }}
     inputRefs:
     - infrastructure
     outputRefs:
     - {{ $dic.name }}
{{- end }}