spokeClusters:
- spoke-1

addonInstallNamespace: open-cluster-management-agent-addon

metrics:
  enabled: true

logging:
  enabled: true
  
  outputs:
    - name: cw-infra
      type: cloudwatch
    - name: loki-infra
      type: loki
      url: https://lokistack-hub-openshift-logging.apps.my-cluster.com

tracing:
  enabled: true
  
  outputs:
    - type: otlphttp
      endpoint: otlp-http-otel-gateway-route-observability.apps.my-cluster.com