collection:
  enabled: false
  # Expects json format
  clfSpec: []

  # List of secrets referenced by clfSpec
  secrets:
    - name: "secret-1"
      # Expects json format
      data: {}
  
  # List of configmaps referenced by clfSpec
  configmaps:
    - name: "configmap-1"
      # Expects json format
      data: {}

storage:
  enabled: false