platform:
  appName: "platform-app"
  prometheusAgentSpec: "some-agent-spec"
  scrapeConfigs:
    - name: "scrape-config-1"
      value: "value-1"
userWorkload:
  appName: "platform-app"
  prometheusAgentSpec: "some-agent-spec"
  scrapeConfigs:
    - name: "scrape-config-1"
      value: "value-1"
prometheusOperator:
  appName: prometheus-operator
  component: controller
  rbacProxyTlsSecret: prometheus-operator-kube-rbac-proxy-tls
  rbacProxyPort: 9092
