{{- if .Values.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-observability-addon:metrics:agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-observability-addon:metrics:agent
subjects:
  - kind: ServiceAccount
    name: metrics-addon-sa
    namespace: {{ .Values.addonInstallNamespace }}
{{- end }}
