# list of spoke clusters
spokeClusters:
  - spoke-1

metrics:
  enabled: false

logging:
  enabled: true

  aws:
    keyID: ID
    keySecret: Secret

  loki:
    enabled: true
    # Loki S3 bucket configuration
    s3Bucket:
      endpoint: https://s3.us-east-1.amazonaws.com
      region: us-east-1
      bucketnames: jmarcal-bucket

tracing:
  enabled: true