{{- if .Values.deployNonOCPStack }}
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-availability.rules.yaml
apiVersion: monitoring.rhobs/v1
kind: PrometheusRule
metadata:
  name: kube-apiserver-availability-rules
  namespace: open-cluster-management-addon-observability
spec:
  {{ (.Files.Glob "files/kube-apiserver-availability.yaml").AsConfig }}

{{- end }}
