{{- if .Values.DeployNonOCPStack }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-state-metrics.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
{{- end }}