{{- if .Values.DeployNonOCPStack }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-state-metrics.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-state-metrics.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}