{{- if .Values.tracing.enabled }}
{{- range $_, $cluster_name := .Values.spokeClusters }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracing-{{ $cluster_name }}-otlphttp
  namespace: {{ $cluster_name }}
  labels:
    mcoa.openshift.io/signal: tracing
  annotations:
    tracing.mcoa.openshift.io/target-output-name: otlphttp
data:
  endpoint: otlp-http-otel-gateway-route-observability.apps.{{ $.Values.hubClusterName }}
{{- end }}
{{- end }}