{{- if or .Values.platformEnabled .Values.userWorkloadsEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acm-prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acm-prometheus-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: {{ .Release.Namespace }}
{{- end }}