{{- if .Values.userWorkloadsEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userWorkload.appName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.userWorkload.rbacProxyTlsSecret }}
  labels:
    app.kubernetes.io/component: user-workload-metrics-collector
    app.kubernetes.io/name: {{ .Values.userWorkload.appName }}
    {{ include "metricshelm.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.userWorkload.rbacProxyPort }}
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: {{ .Values.userWorkload.appName }}
{{- end }}