nameOverride: null

enabled: true

installCOO: false

metrics:
  platformEnabled: false
  userWorkloadsEnabled: false
  uiEnabled: false

logging:
  enabled: false

tracing:
  enabled: false

analytics:
  incidentDetection:
    enabled: false
