{{- if  .Values.deployCOOResources }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acm-prometheus-operator
  labels:
    app.kubernetes.io/component: {{ .Values.prometheusOperator.component }}
    app.kubernetes.io/name: {{ .Values.prometheusOperator.appName }}
    {{ include "metricshelm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acm-prometheus-operator
subjects:
- kind: ServiceAccount
  name: {{ .Values.prometheusOperator.appName }}
  namespace: {{ .Release.Namespace }}
{{- end }}