{{- range $_, $secret_config := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_config.name }}
  namespace: {{ $secret_config.namespace | default $.Release.Namespace}}
  labels:
    {{ include "metricshelm.labels" $ | nindent 4 }}
  {{- with $secret_config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data: {{ fromJson $secret_config.data | toYaml | nindent 2 }}
---
{{- end }}
